package curso.pefinal.VIEW;

import Util.LimitarCaractere;
import Util.Validacoes;
import curso.pefinal.DAO.ClienteDAO;
import curso.pefinal.DAO.TesteCPFDAO;
import curso.pefinal.DTO.ClienteDTO;
import curso.pefinal.DTO.EnderecoDTO;
import curso.pefinal.DTO.LoginDTO;
import curso.pefinal.DTO.TesteCPFDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class CadastroClienteVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public CadastroClienteVIEW() {
        initComponents();
        alterarBtn.setVisible(false);
        cadastrarBtn.setVisible(true);
        cod.setVisible(false);
        codTxt.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        nomeTxt.setDocument(new LimitarCaractere(50, LimitarCaractere.tipoEntrada.NOME));
        senhaTxt.setDocument(new LimitarCaractere(10,LimitarCaractere.tipoEntrada.SENHA));
        ruaTxt.setDocument(new LimitarCaractere(30, LimitarCaractere.tipoEntrada.NOME));
        numeroTxt.setDocument(new LimitarCaractere(5, LimitarCaractere.tipoEntrada.INTEIRO));
        bairroTxt.setDocument(new LimitarCaractere(30, LimitarCaractere.tipoEntrada.NOME));
        complementoTxt.setDocument(new LimitarCaractere(15, LimitarCaractere.tipoEntrada.COMPLEMENTO));
        cidadeTxt.setDocument(new LimitarCaractere(30, LimitarCaractere.tipoEntrada.NOME));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        cadastroLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        CPFLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        estadoLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        ruaLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        CEPLabel = new javax.swing.JLabel();
        complementoLabel = new javax.swing.JLabel();
        bairroTxt = new javax.swing.JTextField();
        cidadeTxt = new javax.swing.JTextField();
        ruaTxt = new javax.swing.JTextField();
        numeroTxt = new javax.swing.JTextField();
        complementoTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        telefoneTxt = new javax.swing.JFormattedTextField();
        CPFTxt = new javax.swing.JFormattedTextField();
        jSeparator18 = new javax.swing.JSeparator();
        estadoTxt = new javax.swing.JComboBox<>();
        CEPTxt = new javax.swing.JFormattedTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        cadastrarBtn = new javax.swing.JButton();
        CPFLabel1 = new javax.swing.JLabel();
        datanascTxt = new javax.swing.JFormattedTextField();
        jSeparator10 = new javax.swing.JSeparator();
        senhaTxt = new javax.swing.JPasswordField();
        alterarBtn = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        cod = new javax.swing.JLabel();
        codTxt = new javax.swing.JTextField();

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator11.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator13.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator17.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cadastroLabel.setBackground(new java.awt.Color(0, 0, 0));
        cadastroLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cadastroLabel.setForeground(new java.awt.Color(0, 0, 0));
        cadastroLabel.setText("CADASTRO");

        nomeLabel.setBackground(new java.awt.Color(153, 153, 153));
        nomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeLabel.setText("NOME:");

        CPFLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPFLabel.setForeground(new java.awt.Color(255, 255, 255));
        CPFLabel.setText("CPF:");

        telefoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        telefoneLabel.setText("TELEFONE:");

        enderecoLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        enderecoLabel.setForeground(new java.awt.Color(153, 153, 153));
        enderecoLabel.setText("ENDEREÇO");

        senhaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(255, 255, 255));
        senhaLabel.setText("SENHA:");

        nomeTxt.setBackground(new java.awt.Color(51, 51, 51));
        nomeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeTxt.setForeground(new java.awt.Color(255, 255, 255));
        nomeTxt.setBorder(null);

        estadoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        estadoLabel.setText("ESTADO:");

        cidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cidadeLabel.setForeground(new java.awt.Color(255, 255, 255));
        cidadeLabel.setText("CIDADE:");

        bairroLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bairroLabel.setForeground(new java.awt.Color(255, 255, 255));
        bairroLabel.setText("BAIRRO:");

        ruaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ruaLabel.setForeground(new java.awt.Color(255, 255, 255));
        ruaLabel.setText("RUA:");

        numeroLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numeroLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeroLabel.setText("NÚMERO:");

        CEPLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CEPLabel.setForeground(new java.awt.Color(255, 255, 255));
        CEPLabel.setText("CEP:");

        complementoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complementoLabel.setForeground(new java.awt.Color(255, 255, 255));
        complementoLabel.setText("COMPLEMENTO:");

        bairroTxt.setBackground(new java.awt.Color(51, 51, 51));
        bairroTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bairroTxt.setForeground(new java.awt.Color(255, 255, 255));
        bairroTxt.setBorder(null);

        cidadeTxt.setBackground(new java.awt.Color(51, 51, 51));
        cidadeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cidadeTxt.setForeground(new java.awt.Color(255, 255, 255));
        cidadeTxt.setBorder(null);

        ruaTxt.setBackground(new java.awt.Color(51, 51, 51));
        ruaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ruaTxt.setForeground(new java.awt.Color(255, 255, 255));
        ruaTxt.setBorder(null);

        numeroTxt.setBackground(new java.awt.Color(51, 51, 51));
        numeroTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numeroTxt.setForeground(new java.awt.Color(255, 255, 255));
        numeroTxt.setBorder(null);

        complementoTxt.setBackground(new java.awt.Color(51, 51, 51));
        complementoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complementoTxt.setForeground(new java.awt.Color(255, 255, 255));
        complementoTxt.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator12.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator15.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator16.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));

        telefoneTxt.setBackground(new java.awt.Color(51, 51, 51));
        telefoneTxt.setBorder(null);
        telefoneTxt.setForeground(new java.awt.Color(255, 255, 255));
        try {
            telefoneTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneTxt.setToolTipText("");
        telefoneTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneTxtActionPerformed(evt);
            }
        });

        CPFTxt.setBackground(new java.awt.Color(51, 51, 51));
        CPFTxt.setBorder(null);
        CPFTxt.setForeground(new java.awt.Color(255, 255, 255));
        try {
            CPFTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPFTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPFTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFTxtActionPerformed(evt);
            }
        });

        jSeparator18.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator18.setForeground(new java.awt.Color(204, 204, 204));

        estadoTxt.setBackground(new java.awt.Color(51, 51, 51));
        estadoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoTxt.setForeground(new java.awt.Color(255, 255, 255));
        estadoTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        estadoTxt.setBorder(null);
        estadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTxtActionPerformed(evt);
            }
        });

        CEPTxt.setBackground(new java.awt.Color(51, 51, 51));
        CEPTxt.setBorder(null);
        CEPTxt.setForeground(new java.awt.Color(255, 255, 255));
        try {
            CEPTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CEPTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CEPTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPTxtActionPerformed(evt);
            }
        });

        jSeparator19.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator19.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator20.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator20.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator21.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator21.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator22.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator22.setForeground(new java.awt.Color(204, 204, 204));

        cadastrarBtn.setBackground(new java.awt.Color(51, 51, 51));
        cadastrarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarBtn.setForeground(new java.awt.Color(0, 0, 0));
        cadastrarBtn.setText("CADASTRAR");
        cadastrarBtn.setBorder(null);
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        CPFLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPFLabel1.setForeground(new java.awt.Color(255, 255, 255));
        CPFLabel1.setText("DATA DE NASCIMENTO:");

        datanascTxt.setBackground(new java.awt.Color(51, 51, 51));
        datanascTxt.setBorder(null);
        datanascTxt.setForeground(new java.awt.Color(255, 255, 255));
        try {
            datanascTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        datanascTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datanascTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanascTxtActionPerformed(evt);
            }
        });

        jSeparator10.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));

        senhaTxt.setBackground(new java.awt.Color(51, 51, 51));
        senhaTxt.setForeground(new java.awt.Color(255, 255, 255));

        alterarBtn.setBackground(new java.awt.Color(51, 51, 51));
        alterarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alterarBtn.setForeground(new java.awt.Color(0, 0, 0));
        alterarBtn.setText("ALTERAR");
        alterarBtn.setBorder(null);
        alterarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarBtnActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        cod.setBackground(new java.awt.Color(153, 153, 153));
        cod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cod.setForeground(new java.awt.Color(255, 255, 255));
        cod.setText("CÓDIGO:");

        codTxt.setBackground(new java.awt.Color(51, 51, 51));
        codTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        codTxt.setForeground(new java.awt.Color(255, 255, 255));
        codTxt.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(enderecoLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cod)
                                                .addGap(110, 110, 110)
                                                .addComponent(codTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(cadastroLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(telefoneLabel)
                                            .addComponent(CPFLabel)
                                            .addComponent(senhaLabel)
                                            .addComponent(estadoLabel)
                                            .addComponent(ruaLabel)
                                            .addComponent(bairroLabel)
                                            .addComponent(numeroLabel)
                                            .addComponent(CEPLabel)
                                            .addComponent(complementoLabel)
                                            .addComponent(cidadeLabel)
                                            .addComponent(CPFLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(complementoTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                                            .addComponent(estadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nomeTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(datanascTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator18, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(telefoneTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                                .addComponent(CPFTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(senhaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jSeparator20, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ruaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                                        .addComponent(bairroTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cidadeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator21, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator22, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(CEPTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator19, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(numeroTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                                                .addGap(116, 116, 116)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(alterarBtn)
                                                    .addComponent(cadastrarBtn)
                                                    .addComponent(btnVoltar)))))
                                    .addComponent(nomeLabel))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(cadastroLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod)
                            .addComponent(codTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel))
                .addGap(2, 2, 2)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFLabel)
                    .addComponent(CPFTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(telefoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFLabel1)
                    .addComponent(datanascTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(enderecoLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(estadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidadeLabel)
                            .addComponent(cidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVoltar))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bairroLabel)
                            .addComponent(bairroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadastrarBtn))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaLabel)
                    .addComponent(ruaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEPLabel)
                    .addComponent(CEPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complementoLabel)
                    .addComponent(complementoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneTxtActionPerformed
        telefoneTxt.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
    }//GEN-LAST:event_telefoneTxtActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        int opcao = 0;
        cadastrarCliente(opcao);
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void CPFTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFTxtActionPerformed
        CPFTxt.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
    }//GEN-LAST:event_CPFTxtActionPerformed

    private void datanascTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanascTxtActionPerformed
        datanascTxt.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
    }//GEN-LAST:event_datanascTxtActionPerformed

    private void CEPTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPTxtActionPerformed
        CEPTxt.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
    }//GEN-LAST:event_CEPTxtActionPerformed

    private void estadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTxtActionPerformed
        
    }//GEN-LAST:event_estadoTxtActionPerformed

    private void alterarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarBtnActionPerformed
        int opcao = 1;
        cadastrarCliente(opcao);
    }//GEN-LAST:event_alterarBtnActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClienteVIEW().setVisible(true);
            }
        });
    }

    private void cadastrarCliente(int opcao){
        TesteCPFDTO teste = new TesteCPFDTO();
        teste.setCpf(CPFTxt.getText());
        
        TesteCPFDAO testecpf = new TesteCPFDAO();
        
        ResultSet rsTesteDAO;
        if(opcao == 0){
            rsTesteDAO = testecpf.testarCPFCadastro(teste);
        } else{
            rsTesteDAO = testecpf.testarCPFAlteracao(teste,Integer.parseInt(codTxt.getText()));
        }
        
        
        
        if(limitaCaractere() == true) try {
            if(rsTesteDAO.next()){
                JOptionPane.showMessageDialog(null, "CPF já cadastrado");
                CPFTxt.requestFocus();
            }
            else{
                
                try{
                    
                    String nome, senha, cpf, telefone, logradouro, cep, bairro, complemento, cidade;
                    int cod, estado;
                    
                    nome = nomeTxt.getText();
                    senha = senhaTxt.getText();
                    cpf = CPFTxt.getText();
                    telefone = telefoneTxt.getText();
                    logradouro = ruaTxt.getText();
                    cep = CEPTxt.getText();
                    bairro = bairroTxt.getText();
                    complemento = complementoTxt.getText();
                    cidade = cidadeTxt.getText();
                    estado = estadoTxt.getSelectedIndex();
                            
                    int numero;
                    numero = Integer.parseInt(numeroTxt.getText());
                    
                    //enviando para a classe
                    
                    EnderecoDTO endereco = new EnderecoDTO();
                    
                    endereco.setRua(logradouro);
                    endereco.setNumero(numero);
                    endereco.setBairro(bairro);
                    endereco.setComplemento(complemento);
                    endereco.setCep(cep);
                    endereco.setCidade(cidade);
                    endereco.setEstado(estado);
                    
                    LoginDTO login = new LoginDTO();
                    login.setPassword(senha);
                    login.setUser(cpf);
                    
                    ClienteDTO cliente = new ClienteDTO();
                    cliente.setNome(nome);
                    cliente.setCpf(cpf);
                    cliente.setTelefone(telefone);
                    cliente.setEndereco(endereco);
                    cliente.setLogin(login);
                    
                    //passando de string para date
                    
                    
                    String dataNascF = datanascTxt.getText();
                    
                    String dia = dataNascF.substring(0, 2);
                    String mes = dataNascF.substring(3, 5);
                    String ano = dataNascF.substring(6);
                    
                    String dataNasc = ano+"-"+mes+"-"+dia;
                    
                    cliente.setData_nasc(dataNasc);
                    
                    if(opcao == 1){
                        cod = Integer.parseInt(codTxt.getText());
                        
                        cliente.setId_cliente(cod);
                    }
                    //enviando para o bd
                    ClienteDAO objClienteDAO = new ClienteDAO();
                    
                    if(opcao == 0){
                        objClienteDAO.cadastrarCliente(cliente);
                        JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!!");
                    }else{
                        objClienteDAO.alterarCliente(cliente);
                        JOptionPane.showMessageDialog(null, "Alterado com Sucesso!!");
                    }
                    
                    dispose();
                }catch(Exception erro){
                    JOptionPane.showMessageDialog(null,"CadastroClienteVIEW: " + erro);
                }
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"TesteCPF: " + erro);
        }
    }
    
    public void alterarClientes(int id){
        
        alterarBtn.setVisible(true);
        cadastrarBtn.setVisible(false);
        cod.setVisible(true);
        codTxt.setVisible(true);
        codTxt.setEditable(false);
        try{
            ClienteDAO cliente = new ClienteDAO();
        
            ClienteDTO clienteDTO = new ClienteDTO();
            clienteDTO = cliente.clienteAlteracao(id);
        
            EnderecoDTO endereco = new EnderecoDTO();
            endereco = clienteDTO.getEndereco();
            
            LoginDTO login = new LoginDTO();
            login = clienteDTO.getLogin();
            
            codTxt.setText(Integer.toString(clienteDTO.getId_cliente()));
            nomeTxt.setText(clienteDTO.getNome());
            CPFTxt.setText(clienteDTO.getCpf());
            datanascTxt.setText(clienteDTO.getData_nasc());
            telefoneTxt.setText(clienteDTO.getTelefone());
            ruaTxt.setText(endereco.getRua());
            numeroTxt.setText(Integer.toString(endereco.getNumero()));
            bairroTxt.setText(endereco.getBairro());
            CEPTxt.setText(endereco.getCep());
            complementoTxt.setText(endereco.getComplemento());
            cidadeTxt.setText(endereco.getCidade());
            estadoTxt.setSelectedIndex(endereco.getEstado());
            senhaTxt.setText(login.getPassword());
            
            
        }
        
        catch(Exception erro){
            
            JOptionPane.showMessageDialog(null, "Alterar CadastroClienteVIEW: " + erro);
        }
        
        
    }
    
    private boolean limitaCaractere(){
        boolean teste = false;
        if(nomeTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome");
            nomeTxt.requestFocus();
        }else if(CPFTxt.getText().replaceAll("[^0-9]", "").length() == 0){
            JOptionPane.showMessageDialog(null, "Preencha o CPF");
            CPFTxt.requestFocus();
        }else if(datanascTxt.getText().replaceAll("[^0-9]", "").length() == 0){
            JOptionPane.showMessageDialog(null, "Preencha a Data de Nascimento");
            datanascTxt.requestFocus();
        }else if(telefoneTxt.getText().replaceAll("[^0-9]", "").length() == 0){
            JOptionPane.showMessageDialog(null, "Preencha o Telefone");
            telefoneTxt.requestFocus();
        }else if(ruaTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Rua");
            ruaTxt.requestFocus();
        }else if(numeroTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Número");
            numeroTxt.requestFocus();
        }else if(bairroTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Bairro");
            bairroTxt.requestFocus();
        }else if(CEPTxt.getText().replaceAll("[^0-9]", "").length() == 0){
            JOptionPane.showMessageDialog(null, "Preencha o CEP");
            CEPTxt.requestFocus();
        }else if(complementoTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Complemento");
            complementoTxt.requestFocus();
        }else if(cidadeTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Cidade");
            cidadeTxt.requestFocus();
        }else if(!(CPFTxt.getText().replaceAll("[^0-9]", "").length() == 11) ){
            JOptionPane.showMessageDialog(null, "Tamanho do CPF menor do que o permitido");
            CPFTxt.requestFocus();
        }else if(senhaTxt.getText().length() < 4){
            JOptionPane.showMessageDialog(null, "Tamanho da Senha menor do que o permitido");
            senhaTxt.requestFocus();
        }else if(!(telefoneTxt.getText().replaceAll("[^0-9]", "").length() == 11 || telefoneTxt.getText().replaceAll("[^0-9]", "").length() == 10) ){
            JOptionPane.showMessageDialog(null, "Tamanho do Telefone menor do que o permitido");
            telefoneTxt.requestFocus();
        }else if(!(datanascTxt.getText().replaceAll("[^0-9]", "").length() == 8) ){
            JOptionPane.showMessageDialog(null, "Tamanho da data menor do que a permitida");
            datanascTxt.requestFocus();
        }else if(Validacoes.CPFVerdadeiro(CPFTxt.getText().replaceAll("[^0-9]", "")) == false ){
            JOptionPane.showMessageDialog(null, "CPF inválido");
            CPFTxt.requestFocus();
        }else if(Validacoes.dataVerdadeira(datanascTxt.getText()) == false ){
            JOptionPane.showMessageDialog(null, "Data inválida");
            datanascTxt.requestFocus();
        }else if(estadoTxt.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Nenhum Estado Selecionado");
            estadoTxt.requestFocus();
        }else{
            teste = true;
        }
        
        return teste;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEPLabel;
    private javax.swing.JFormattedTextField CEPTxt;
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JLabel CPFLabel1;
    private javax.swing.JFormattedTextField CPFTxt;
    private javax.swing.JButton alterarBtn;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTxt;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JLabel cadastroLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTxt;
    private javax.swing.JLabel cod;
    private javax.swing.JTextField codTxt;
    private javax.swing.JLabel complementoLabel;
    private javax.swing.JTextField complementoTxt;
    private javax.swing.JFormattedTextField datanascTxt;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JComboBox<String> estadoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JTextField ruaTxt;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaTxt;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JFormattedTextField telefoneTxt;
    // End of variables declaration//GEN-END:variables
}
