package curso.pefinal.VIEW;

import curso.pefinal.DAO.FuncionarioDAO;
import curso.pefinal.DAO.TesteAgendamentoDAO;
import curso.pefinal.DTO.FuncionarioDTO;
import curso.pefinal.DTO.TesteAgendamentoDTO;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conta
 */
public class TabelaFuncionarioVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Tabela
     */
    public TabelaFuncionarioVIEW() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        listarFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbfuncionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluie = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tbfuncionario.setBackground(new java.awt.Color(51, 51, 51));
        tbfuncionario.setForeground(new java.awt.Color(255, 255, 255));
        tbfuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CPF", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbfuncionario.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tbfuncionario.setShowGrid(true);
        tbfuncionario.setShowHorizontalLines(false);
        tbfuncionario.setShowVerticalLines(false);
        tbfuncionario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbfuncionario);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES CADASTRADOS");

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluie.setText("EXCLUIR");
        btnExcluie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluieActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluie)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(332, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluie)
                    .addComponent(btnCadastrar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        new CadastroClienteVIEW().setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluieActionPerformed
        excluirFuncionarios();
        listarFuncionarios();
    }//GEN-LAST:event_btnExcluieActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        alterarFuncionarios();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaFuncionarioVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluie;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbfuncionario;
    // End of variables declaration//GEN-END:variables

     private void listarFuncionarios(){
        try{
            FuncionarioDAO funcionario = new FuncionarioDAO();
            DefaultTableModel model = (DefaultTableModel) tbfuncionario.getModel();
            
            model.setNumRows(0);
            ArrayList<FuncionarioDTO> funcionarios = new ArrayList<>();
            funcionarios = funcionario.listarFuncionario();
            
            for(int cont = 0; cont < funcionarios.size(); cont++){
                model.addRow(new Object[]{
                    funcionarios.get(cont).getId_funcionario(),
                    funcionarios.get(cont).getNome(),
                    funcionarios.get(cont).getCpf(),
                    funcionarios.get(cont).getTelefone()
                        
                });
            }
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "TabelaClienteVIEW: " + erro);
        }

    }
    
    private void alterarFuncionarios(){
        
        String idInicial;
        int selecionar = tbfuncionario.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbfuncionario.getModel();
        idInicial = model.getValueAt(selecionar, 0).toString();
        int id = Integer.parseInt(idInicial);
                
        CadastroFuncionarioVIEW cadFun = new CadastroFuncionarioVIEW();
        cadFun.setVisible(true);
        cadFun.alterarFuncionarios(id);
        
        dispose();
    }
    
    private void excluirFuncionarios(){
        String idInicial;
        int selecionar = tbfuncionario.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbfuncionario.getModel();

        //retorna o valor no campo da linha selecionar e da coluna 0
        idInicial = model.getValueAt(selecionar, 0).toString();
        int id = Integer.parseInt(idInicial);
        try{

            TesteAgendamentoDTO teste = new TesteAgendamentoDTO();
            teste.setId(id);

            TesteAgendamentoDAO testeagen = new TesteAgendamentoDAO();

            ResultSet rsTesteDAO;
            rsTesteDAO = testeagen.testarAgendamentoFuncionario(teste);
            
            if(rsTesteDAO.next()){
                JOptionPane.showMessageDialog(null, "Não é possível fazer a exclusão\nO Funcionario possui agendamento");
            }else{
                FuncionarioDAO funcionario = new FuncionarioDAO();
            
                Object[] opcoes = { "Sim", "Não" }; 
                int resposta = JOptionPane.showOptionDialog(null, "Confirma a Exclusão?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
                if(resposta == 0){
                    funcionario.excluirFuncionario(id);
                }
            }
            
            
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Excluir FuncionarioVIEW: " + erro);
        }
    }
}
